version: "3.9"

services:
  mc:
    container_name: papermc
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      TZ: Asia/Tokyo
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.9"
      MAX_MEMORY: "8G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "test"
      RCON_PORT: 25575
    stdin_open: true
    tty: true
