version: '3.9'

services:
  mc:
    container_name: minecraft-server
    build:
      dockerfile: docker/mc/Dockerfile
      context: .
    ports:
      - '25565:25565'
    volumes:
      - type: bind
        source: ./data
        target: /server
    working_dir: /server
    command: java -jar papermc.jar
